Adds docker base images and docs
MVPStudio/main pull request #1
Opened 2018-06-04 01:49 UTC by oliverdain

I've already got the Childen's museum stuff running inside that node container. Adding that to the repo will happen in the next commit.

2018-06-06 17:31 UTC, slively requested changes

2018-06-06 17:31 UTC, slively commented on docker/base/Dockerfile
> +       useradd -ms /bin/bash revl
mvp instead of revl?

2018-06-06 17:31 UTC, slively commented on docker/README.md
> +apps in Docker containers as root. Thus we run all apps as the `revl` user (which is created in our base image).
mvp instead of revl?

2018-06-09 17:17 UTC, oliverdain commented on docker/base/Dockerfile
> +       useradd -ms /bin/bash revl
done

2018-06-09 17:22 UTC, merged